# Common blocks used by jobs

version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.16.3

# Actual job definitions
jobs:
  # Setup npmrc, restore caches, npm ci
  install:
    executor: node
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
              sudo npm install -g npm@6.10.2
              npm ci
            fi
            npx gen-dev-id -o .dev-unique-id

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint_test_other:
    working_directory: ~/folio-service
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Lint"
          command: |
            npm run lint

  test:
    working_directory: ~/folio-service
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: "Test"
          command: |
            npm run test:junit -- --reporter-options mochaFile=reports/mocha/test-results.xml

      - store_test_results:
          path: reports

workflows:
  version: 2
  build:
    jobs:
      - install:
      - test:
          requires:
            - install
      - lint_test_other:
          requires:
            - install
